# Basic Set Operation

In [1]:
# Example Sets 
A = {0, 2, 4, 6, 8}
B = {1, 2, 3, 4, 5} 
  
# union of above sets 
print("Union :", A | B) 
  
# intersection of above sets
print("Intersection :", A & B) 
  
# difference between above sets
print("Difference :", A - B)

Union : {0, 1, 2, 3, 4, 5, 6, 8}
Intersection : {2, 4}
Difference : {0, 8, 6}


# Trapezoidal Membership Function

In [2]:
import numpy as np
import skfuzzy as sk

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for Trapezoidal membership functions
qual_lo = sk.trapmf(x_qual, [0, 0, 5,5])

# Gaussian Membership Function

In [3]:
import numpy as np
import skfuzzy as sk

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for Gaussian membership functions
qual_lo = sk.gaussmf(x_qual, np.mean(x_qual), np.std(x_qual))


# Generalized Bell membership function

In [4]:
import numpy as np
import skfuzzy as sk

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for Generalized Bell membership functions
qual_lo = sk.gbellmf(x_qual, 0.5, 0.5, 0.5)


# Sigmoid Membership Function

In [5]:
import numpy as np
import skfuzzy as sk

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for Sigmoid membership functions
qual_lo = sk.sigmf(x_qual, 0.5,0.5)


# Fuzzy OR Operation

In [7]:
import skfuzzy as sk
import numpy as np

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for two membership functions (Triangular)
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])

#Finding the Maximum (Fuzzy Or)
sk.fuzzy_or(x_qual,qual_lo,x_qual,qual_md)


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1. , 0.8, 0.6, 0.6, 0.8, 1. , 0.8, 0.6, 0.4, 0.2, 0. ]))

# Fuzzy AND Operation

In [8]:
import skfuzzy as sk
import numpy as np

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for two membership functions (Triangular)
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])

#Finding the Minimum (Fuzzy AND)
sk.fuzzy_and(x_qual,qual_lo,x_qual,qual_md)


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0. , 0.2, 0.4, 0.4, 0.2, 0. , 0. , 0. , 0. , 0. , 0. ]))

# Fuzzy NOT Operation

In [9]:
import skfuzzy as sk
import numpy as np

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for two membership functions (Triangular)
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])

#Finding the Complement (Fuzzy NOT)
sk.fuzzy_not(qual_lo)


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1. , 1. , 1. , 1. , 1. ])

# Fuzzy Cartesian Operation

In [11]:
import skfuzzy as sk
import numpy as np

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for two membership functions (Triangular)
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])

#Finding the Product (Fuzzy Cartesian)
sk.cartprod(qual_lo, qual_md)


array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 0.8, 0.8, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.6, 0.6, 0.6, 0.6, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

# Fuzzy Subtract Operation

In [13]:
import skfuzzy as sk
import numpy as np

#Defining the Numpy array for Tip Quality
x_qual = np.arange(0, 11, 1)

#Defining the Numpy array for two membership functions (Triangular)
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])

#Finding the Difference (Fuzzy Subtract)
sk.fuzzy_sub(x_qual,qual_lo,x_qual,qual_md)


(array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
          1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 0.8, 0.8, 0.6, 0.6, 0.4, 0.4, 0.2,
        0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. ]))